Install dependencies
We don't really need to authenticate with npm, but not setting the token
results in the error:
```
Error: Failed to replace env in config: ${NPM_TOKEN}
```

Also use `npm ci` to install dependencies, like we do in the release
action.